"""empty message

Revision ID: 763313db36c2
Revises: cb04a51b7bc4
Create Date: 2026-04-23 16:38:13.074924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763313db36c2'
down_revision = 'cb04a51b7bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_cart_items_cart_id", 'product', ['product_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
